# example netlify.toml
[build]
  publish = "build"

  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/master/docs/netlify-dev.md#project-detection
  [dev]
  # command = "yarn start" # Command to start your dev server
    port = 3000 # Port that the dev server will be listening on
    publish = "dist" # Folder with the static content for _redirect file

  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[redirects]]
from = "/article/styl-zycia-oraz-zmiany-ogolnoustrojowe-u-kobiet-w-ciazy"
to = "/index.html"
status = 200